#🐼 Day 33 — Pandas Indexing & Data Selection

##Day 31 → Series
##Day 32 → DataFrame Basics
#👉 Day 33 → DataFrame se specific rows/columns select karna

##Iske baad Day 34 se real CSV/Kaggle dataset par kaam start karenge.

#🎯 Day 33 Goals

##Aaj hum seekhenge:

###DataFrame indexing
###loc[]
###iloc[]
###Row selection
###Column selection
###Row + column selection
###Slicing
###Conditional selection
###Multiple conditions
###isin()
###query()
###Practical data-analysis examples

#1️⃣ Create a DataFrame

##Sabse pehle ek dataset banate hain:

In [1]:
import pandas as pd

students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Age": [20, 21, 20, 22, 21],
    "Python": [85, 72, 91, 64, 78],
    "Math": [80, 68, 94, 70, 75],
    "DSA": [82, 70, 89, 65, 80]
})

print(students)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
1   Aman   21      72    68   70
2  Priya   20      91    94   89
3   Neha   22      64    70   65
4  Rohit   21      78    75   80

#🧠 Important:
DataFrame mein:

rows → students

columns → Name, Age, Python, Math, DSA

index → 0, 1, 2, 3, 4

#2️⃣ Selecting One Column

In [2]:
print(students["Name"])

0    Rahul
1     Aman
2    Priya
3     Neha
4    Rohit
Name: Name, dtype: object

In [3]:
print(students["Python"])

0    85
1    72
2    91
3    64
4    78
Name: Python, dtype: int64

#3️⃣ Selecting Multiple Columns

##Multiple columns ke liye list use karte hain:

In [4]:
print(students[["Name", "Python", "Math"]])

    Name  Python  Math
0  Rahul      85    80
1   Aman      72    68
2  Priya      91    94
3   Neha      64    70
4  Rohit      78    75

#🧠 Mind Template

###One column

↓

####df["column"]

###Multiple columns

↓

####df[["column1", "column2"]]

#4️⃣ loc[] — Label Based Selection

##loc[] ka use label/index name ke basis par selection ke liye hota hai.

In [5]:
print(students.loc[2])

Name      Priya
Age          20
Python       91
Math         94
DSA          89
Name: 2, dtype: object

#5️⃣ Select Multiple Rows Using loc

In [6]:
print(students.loc[[0, 2, 4]])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89
4  Rohit   21      78    75   80

#6️⃣ iloc[] — Position Based Selection

##iloc ka matlab basically integer-location based indexing.

In [7]:
print(students.iloc[0])

Name      Rahul
Age          20
Python       85
Math         80
DSA          82
Name: 0, dtype: object

In [8]:
print(students.iloc[2])

Name      Priya
Age          20
Python       91
Math         94
DSA          89
Name: 2, dtype: object

#7️⃣ loc vs iloc

##Suppose:

In [9]:
students.loc[2]

Name      Priya
Age          20
Python       91
Math         94
DSA          89
Name: 2, dtype: object

##means:

index label 2

In [10]:
students.iloc[2]

Name      Priya
Age          20
Python       91
Math         94
DSA          89
Name: 2, dtype: object

#means:

position 2

##Default index 0,1,2,3,4 hone ki wajah se abhi dono same result denge.

##Lekin custom index ke saath difference important ho jata hai.

#8️⃣ Select Rows Using iloc

###First 3 rows:

In [11]:
print(students.iloc[0:3])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
1   Aman   21      72    68   70
2  Priya   20      91    94   89

##Last two rows:

In [12]:
print(students.iloc[-2:])

    Name  Age  Python  Math  DSA
3   Neha   22      64    70   65
4  Rohit   21      78    75   80

#9️⃣ Select Specific Row + Column

##Suppose humein Priya ka Python score chahiye.

##Using loc:

In [13]:
print(students.loc[2, "Python"])

91

##Using iloc:

In [14]:
print(students.iloc[2, 2])

91

#🔟 Select Multiple Rows + Columns

##Using loc:

In [15]:
print(students.loc[0:2, ["Name", "Python"]])

    Name  Python
0  Rahul      85
1   Aman      72
2  Priya      91

##Using iloc:

In [16]:
print(students.iloc[0:3, 0:3])

    Name  Age  Python
0  Rahul   20      85
1   Aman   21      72
2  Priya   20      91

#1️⃣1️⃣ Row Slicing

##First three rows:

In [17]:
print(students.iloc[:3])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
1   Aman   21      72    68   70
2  Priya   20      91    94   89

In [18]:
print(students.iloc[1:4])

    Name  Age  Python  Math  DSA
1   Aman   21      72    68   70
2  Priya   20      91    94   89
3   Neha   22      64    70   65

In [19]:
print(students.iloc[-3:])

    Name  Age  Python  Math  DSA
2  Priya   20      91    94   89
3   Neha   22      64    70   65
4  Rohit   21      78    75   80

#1️⃣2️⃣ Conditional Selection

##Ab real Data Analysis wali power start hoti hai.

##Suppose humein students chahiye jinke Python marks 80 se greater hain.

In [20]:
print(students[students["Python"] > 80])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89

#🧠 Mind Template:

Condition

↓

students["Python"] > 80

↓

Boolean Series

↓

students[condition]

↓

Filtered DataFrame

#1️⃣3️⃣ Python Marks >= 80

In [21]:
high_python = students[students["Python"] >= 80]

print(high_python)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89

#1️⃣4️⃣ Python Marks < 70

In [22]:
print(students[students["Python"] < 70])

   Name  Age  Python  Math  DSA
3  Neha   22      64    70   65

#1️⃣5️⃣ Multiple Conditions

Suppose:

Python >= 80 AND Math >= 80

In [23]:
result = students[
    (students["Python"] >= 80) &
    (students["Math"] >= 80)
]

print(result)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89

#1️⃣6️⃣ OR Condition

##Python >= 90 OR Math >= 90:

In [24]:
result = students[
    (students["Python"] >= 90) |
    (students["Math"] >= 90)
]

print(result)

    Name  Age  Python  Math  DSA
2  Priya   20      91    94   89

#1️⃣7️⃣ NOT Condition

##Python marks 80 or above ko exclude karna:

In [25]:
result = students[
    ~(students["Python"] >= 80)
]

print(result)

    Name  Age  Python  Math  DSA
1   Aman   21      72    68   70
3   Neha   22      64    70   65
4  Rohit   21      78    75   80

#1️⃣8️⃣ isin()

##Suppose humein sirf Rahul aur Priya ka data chahiye.

In [26]:
result = students[
    students["Name"].isin(["Rahul", "Priya"])
]

print(result)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89

#1️⃣9️⃣ query()

##Pandas mein conditions likhne ka ek clean way:

In [27]:
result = students.query("Python >= 80")

print(result)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89

In [28]:
result = students.query(
    "Python >= 80 and Math >= 80"
)

print(result)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89

#2️⃣0️⃣ Selecting Specific Columns After Filtering

##Suppose humein sirf Name + Python chahiye jahan Python >= 80 hai:

In [29]:
result = students.loc[
    students["Python"] >= 80,
    ["Name", "Python"]
]

print(result)

    Name  Python
0  Rahul      85
2  Priya      91

#2️⃣1️⃣ Practical Data Analysis Example

##Suppose company ke employees ka dataset hai:

In [30]:
employees = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Neha", "Rohit"],
    "Department": ["IT", "HR", "IT", "Finance", "IT"],
    "Salary": [50000, 45000, 70000, 55000, 65000],
    "Experience": [2, 3, 5, 4, 6]
})

print(employees)

    Name Department  Salary  Experience
0   Aman         IT   50000           2
1   Riya         HR   45000           3
2  Karan         IT   70000           5
3   Neha    Finance   55000           4
4  Rohit         IT   65000           6

In [31]:
# IT EMPLOYEE
it_employees = employees[
    employees["Department"] == "IT"
]

print(it_employees)

    Name Department  Salary  Experience
0   Aman         IT   50000           2
2  Karan         IT   70000           5
4  Rohit         IT   65000           6

In [33]:
# SALARY>60000
high_salary = employees[
    employees["Salary"] > 60000
]

print(high_salary)

    Name Department  Salary  Experience
2  Karan         IT   70000           5
4  Rohit         IT   65000           6

In [34]:
# IT + SALARY>60000
result = employees[
    (employees["Department"] == "IT") &
    (employees["Salary"] > 60000)
]

print(result)

    Name Department  Salary  Experience
2  Karan         IT   70000           5
4  Rohit         IT   65000           6

#🧠 Day 33 Mind Template

DataFrame

    ↓

Understand rows & columns

    ↓

Select columns

    ↓

Select rows

    ↓

loc / iloc

    ↓

Row + Column selection

    ↓

Apply conditions

    ↓

Multiple conditions

    ↓

Filter relevant data

    ↓

Analyze

# QUICK CHEAT SHEET:

In [35]:
# Column
#df["column"]

# Multiple columns
#df[["col1", "col2"]]

# loc
#df.loc[row_label]
#df.loc[row_label, "column"]

# iloc
#df.iloc[row_position]
#df.iloc[row_position, column_position]

# Condition
#df[df["column"] > value]

# AND
#df[(condition1) & (condition2)]

# OR
#df[(condition1) | (condition2)]

# NOT
#df[~condition]

# Multiple values
#df[df["column"].isin(["A", "B"])]

# Query
#df.query("column > value")

#📝 Day 33 Practice
##Q1

##Create a DataFrame containing:

###Name
###Age
###Marks

##Select only the Name column.

In [36]:
data=pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Age": [20, 21, 20, 22, 21],
    "Marks": [85, 72, 91, 64, 78]
})
print(data["Name"])

0    Rahul
1     Aman
2    Priya
3     Neha
4    Rohit
Name: Name, dtype: object

#Q2

##Select Name and Marks columns together.

In [38]:
data[["Name","Marks"]]

    Name  Marks
0  Rahul     85
1   Aman     72
2  Priya     91
3   Neha     64
4  Rohit     78

#Q3

##Using loc, select the third row.

In [40]:
print(data.loc[2])

Name     Priya
Age         20
Marks       91
Name: 2, dtype: object

#Q4

##Using iloc, select the fourth row.

In [41]:
print(data.iloc[3])

Name     Neha
Age        22
Marks      64
Name: 3, dtype: object

#Q5

##Select the first three rows using iloc.

In [42]:
print(data.iloc[0:3])

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91

#Q6

##Select students whose marks are greater than 75.

In [45]:
good_student=data["Marks"]>75
print(data.loc[good_student])

    Name  Age  Marks
0  Rahul   20     85
2  Priya   20     91
4  Rohit   21     78

#Q7

##Select students whose marks are between 60 and 80.

###Hint: Use two conditions.

In [47]:
print(data[(data["Marks"]>=60) & (data["Marks"]<=80)])

    Name  Age  Marks
1   Aman   21     72
3   Neha   22     64
4  Rohit   21     78

#Q8

##Select students whose:

###Python >= 80
###AND
###Math >= 75

In [52]:
students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Age": [20, 21, 20, 22, 21],
    "Python": [85, 72, 91, 64, 78],
    "Math": [80, 68, 94, 70, 75],
    "DSA": [82, 70, 89, 65, 80]
})

result = students.query("Python >= 80 and Math >= 80")
print(result)

#OR
result=students[(students["Python"]>=80) & (students["Math"]>=80)]
print(result)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89
    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89

#Q9

##Using isin(), select students whose names are:

###"Rahul", "Priya"

In [53]:
students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Age": [20, 21, 20, 22, 21],
    "Python": [85, 72, 91, 64, 78],
    "Math": [80, 68, 94, 70, 75],
    "DSA": [82, 70, 89, 65, 80]
})
print(students[students["Name"].isin(["Rahul","Priya"])])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89

#Q10 — Mini Data Analysis Task 🔥

##Create this DataFrame:

###Name
###Age
###Python
###Math
###DSA

##At least 8 students.

##Then find:

###Students with Python >= 80
###Students with Math >= 75
###Students with Python >= 80 AND Math >= 80
###Students younger than 21

In [54]:
students=pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit","Sahil","Mohit","Sagar"],
    "Age": [20, 21, 20, 22, 21,20,21,20],
    "Python": [85, 72, 91, 64, 79, 88, 90, 99],
    "Math": [80, 68, 94, 70, 75, 88, 90, 99],
    "DSA": [82, 70, 89, 65, 80, 88, 90, 99]
})
print(students)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
1   Aman   21      72    68   70
2  Priya   20      91    94   89
3   Neha   22      64    70   65
4  Rohit   21      79    75   80
5  Sahil   20      88    88   88
6  Mohit   21      90    90   90
7  Sagar   20      99    99   99

In [55]:
high_python=students['Python']>=80
print(students.loc[high_python])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89
5  Sahil   20      88    88   88
6  Mohit   21      90    90   90
7  Sagar   20      99    99   99

In [56]:
high_math=students['Math']>=75
print(students.loc[high_math])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89
4  Rohit   21      79    75   80
5  Sahil   20      88    88   88
6  Mohit   21      90    90   90
7  Sagar   20      99    99   99

In [57]:
print(students[(students["Python"]>=80) & (students["Math"]>=80)])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89
5  Sahil   20      88    88   88
6  Mohit   21      90    90   90
7  Sagar   20      99    99   99

In [59]:
younger_student=students["Age"]<21
print(students.loc[younger_student])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
2  Priya   20      91    94   89
5  Sahil   20      88    88   88
7  Sagar   20      99    99   99