#1️⃣ Sabse pehle Real Dataset

##Aaj ek real-world CSV dataset download/use karna hai.

In [1]:
from google.colab import files

uploaded = files.upload()

Saving sales.csv to sales.csv

In [2]:
import pandas as pd
df = pd.read_csv("sales.csv")

#2️⃣ Dataset Load Hone Ke Baad

#Sabse pehle:

print(df)

##Lekin large dataset mein pura DataFrame print mat karna.

#Instead:

print(df.head())

#3️⃣ head()

In [3]:
df.head()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax,total_price,reward_points
0,1,A,New York,Member,Male,Shampoo,Personal Care,5.50,3,1.16,17.66,1
1,2,B,Los Angeles,Normal,Female,Notebook,Stationery,2.75,10,1.93,29.43,0
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26,19.26,1
3,4,A,Chicago,Normal,Male,Detergent,Household,7.80,5,2.73,41.73,0
4,5,B,Los Angeles,Member,Female,Orange Juice,Beverages,3.50,7,1.72,26.22,2

In [5]:
df.head(10)

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax,total_price,reward_points
0,1,A,New York,Member,Male,Shampoo,Personal Care,5.50,3,1.16,17.66,1
1,2,B,Los Angeles,Normal,Female,Notebook,Stationery,2.75,10,1.93,29.43,0
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26,19.26,1
3,4,A,Chicago,Normal,Male,Detergent,Household,7.80,5,2.73,41.73,0
4,5,B,Los Angeles,Member,Female,Orange Juice,Beverages,3.50,7,1.72,26.22,2
5,6,A,Chicago,Normal,Male,Shampoo,Stationery,11.24,9,7.08,108.24,0
6,7,A,Chicago,Normal,Male,Shampoo,Personal Care,10.71,1,0.75,11.46,0
7,8,B,Los Angeles,Normal,Female,Shampoo,Household,18.23,9,11.48,175.55,0
8,9,A,Chicago,Member,Female,Apple,Fruits,14.15,20,19.81,302.81,30
9,10,B,Los Angeles,Member,Male,Shampoo,Fruits,18.42,19,24.50,374.48,37

#🧠 Mind:

head()

↓

Dataset ke starting rows

#4️⃣ tail()

##Dataset ke last rows dekhne ke liye:

In [4]:
df.tail()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax,total_price,reward_points
995,996,A,New York,Member,Female,Shampoo,Stationery,1.55,11,1.19,18.24,1
996,997,A,New York,Member,Male,Detergent,Personal Care,2.44,7,1.20,18.28,1
997,998,A,New York,Member,Female,Shampoo,Stationery,17.92,2,2.51,38.35,3
998,999,A,New York,Member,Female,Shampoo,Beverages,17.41,4,4.87,74.51,7
999,1000,A,New York,Normal,Male,Orange Juice,Stationery,4.11,4,1.15,17.59,0

In [6]:
df.tail(10)

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax,total_price,reward_points
990,991,A,Chicago,Normal,Female,Detergent,Stationery,8.18,1,0.57,8.75,0
991,992,A,New York,Normal,Male,Notebook,Household,11.33,9,7.14,109.11,0
992,993,A,New York,Normal,Female,Apple,Stationery,4.59,19,6.10,93.31,0
993,994,A,New York,Normal,Female,Orange Juice,Personal Care,5.16,13,4.70,71.78,0
994,995,A,New York,Member,Male,Notebook,Personal Care,6.60,5,2.31,35.31,3
995,996,A,New York,Member,Female,Shampoo,Stationery,1.55,11,1.19,18.24,1
996,997,A,New York,Member,Male,Detergent,Personal Care,2.44,7,1.20,18.28,1
997,998,A,New York,Member,Female,Shampoo,Stationery,17.92,2,2.51,38.35,3
998,999,A,New York,Member,Female,Shampoo,Beverages,17.41,4,4.87,74.51,7
999,1000,A,New York,Normal,Male,Orange Juice,Stationery,4.11,4,1.15,17.59,0

#5️⃣ Dataset ka Size — shape

In [7]:
df.shape

(1000, 12)

In [9]:
df.shape[0] #-> Rows

1000

In [10]:
df.shape[1] #-> Columns

12

#6️⃣ Column Names

In [11]:
df.columns

Index(['sale_id', 'branch', 'city', 'customer_type', 'gender', 'product_name',
       'product_category', 'unit_price', 'quantity', 'tax', 'total_price',
       'reward_points'],
      dtype='object')

####Agar List Chahiye:

In [12]:
df.columns.tolist()

['sale_id',
 'branch',
 'city',
 'customer_type',
 'gender',
 'product_name',
 'product_category',
 'unit_price',
 'quantity',
 'tax',
 'total_price',
 'reward_points']

#7️⃣ Dataset Information — info()

##Ye Day 34 ka sabse important function hai.

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sale_id           1000 non-null   int64
 1   branch            1000 non-null   object
 2   city              1000 non-null   object
 3   customer_type     1000 non-null   object
 4   gender            1000 non-null   object
 5   product_name      1000 non-null   object
 6   product_category  1000 non-null   object
 7   unit_price        1000 non-null   float64
 8   quantity          1000 non-null   int64
 9   tax               1000 non-null   float64
 10  total_price       1000 non-null   float64
 11  reward_points     1000 non-null   int64
dtypes: float64(3), int64(3), object(6)
memory usage: 93.9+ KB

#8️⃣ Data Types

In [15]:
df.dtypes

sale_id               int64
branch               object
city                 object
customer_type        object
gender               object
product_name         object
product_category     object
unit_price          float64
quantity              int64
tax                 float64
total_price         float64
reward_points         int64
dtype: object

#9️⃣ Statistical Summary

##Numerical columns ke liye:

In [16]:
df.describe()

,sale_id,unit_price,quantity,tax,total_price,reward_points
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,10.836110,10.337000,7.758010,118.583900,6.057000
std,288.819436,5.775924,6.029908,6.538066,99.936441,9.350464
min,1.000000,1.020000,1.000000,0.080000,1.210000,0.000000
25%,250.750000,5.867500,5.000000,2.510000,38.380000,0.000000
50%,500.500000,10.615000,10.000000,5.870000,89.705000,0.000000
75%,750.250000,15.882500,16.000000,11.522500,176.072500,10.000000
max,1000.000000,20.980000,20.000000,28.390000,433.990000,43.000000

#🔟 Missing Values

In [17]:
df.isnull()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax,total_price,reward_points
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
df.isnull().sum()

sale_id             0
branch              0
city                0
customer_type       0
gender              0
product_name        0
product_category    0
unit_price          0
quantity            0
tax                 0
total_price         0
reward_points       0
dtype: int64

#1️⃣1️⃣ Duplicate Rows

In [19]:
df.duplicated().sum()

np.int64(0)

###Actual duplicate rows dekhne ke liye:

In [21]:
df[df.duplicated()]

Empty DataFrame
Columns: [sale_id, branch, city, customer_type, gender, product_name, product_category, unit_price, quantity, tax, total_price, reward_points]
Index: []

#1️⃣2️⃣ Unique Values

##Suppose dataset mein Category column hai:

In [23]:
df["branch"].unique()

array(['A', 'B'], dtype=object)

In [24]:
df["city"].unique()

array(['New York', 'Los Angeles', 'Chicago'], dtype=object)

In [25]:
df["customer_type"].unique()

array(['Member', 'Normal'], dtype=object)

In [26]:
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [27]:
df["product_category"].unique()

array(['Personal Care', 'Stationery', 'Fruits', 'Household', 'Beverages'],
      dtype=object)

In [28]:
df["product_name"].unique()

array(['Shampoo', 'Notebook', 'Apple', 'Detergent', 'Orange Juice'],
      dtype=object)

#1️⃣2️⃣ Number of Unique Values

In [29]:
print("Branches:", df["branch"].nunique())
print("Cities:", df["city"].nunique())
print("Customer Types:", df["customer_type"].nunique())
print("Gender:", df["gender"].nunique())
print("Product Categories:", df["product_category"].nunique())
print("Products:", df["product_name"].nunique())

Branches: 2
Cities: 3
Customer Types: 2
Gender: 2
Product Categories: 5
Products: 5

#13️⃣ Value Counts

##Ab dekhte hain kitni sales kis branch se hain:

In [30]:
df["branch"].value_counts()

branch
A    674
B    326
Name: count, dtype: int64

In [31]:
df["city"].value_counts()

city
New York       344
Chicago        330
Los Angeles    326
Name: count, dtype: int64

In [33]:
df["customer_type"].value_counts()

customer_type
Member    516
Normal    484
Name: count, dtype: int64

In [34]:
df["gender"].value_counts()

gender
Male      528
Female    472
Name: count, dtype: int64

In [35]:
df["product_category"].value_counts()

product_category
Fruits           209
Personal Care    208
Stationery       198
Household        198
Beverages        187
Name: count, dtype: int64

In [36]:
df["product_name"].value_counts()

product_name
Shampoo         224
Orange Juice    208
Notebook        194
Detergent       189
Apple           185
Name: count, dtype: int64

#14️⃣ Numerical columns ko samjho

In [37]:
df[[
    "unit_price",
    "quantity",
    "tax",
    "total_price",
    "reward_points"
]].describe()

        unit_price     quantity          tax  total_price  reward_points
count  1000.000000  1000.000000  1000.000000  1000.000000    1000.000000
mean     10.836110    10.337000     7.758010   118.583900       6.057000
std       5.775924     6.029908     6.538066    99.936441       9.350464
min       1.020000     1.000000     0.080000     1.210000       0.000000
25%       5.867500     5.000000     2.510000    38.380000       0.000000
50%      10.615000    10.000000     5.870000    89.705000       0.000000
75%      15.882500    16.000000    11.522500   176.072500      10.000000
max      20.980000    20.000000    28.390000   433.990000      43.000000

#15️⃣ Total Business Metrics

###Total Revenue:

In [38]:
df["total_price"].sum()

np.float64(118583.9)

###Total Quantity Sold:

In [39]:
df["quantity"].sum()

np.int64(10337)

###Average Transaction Value:

In [40]:
df["total_price"].mean()

np.float64(118.5839)

###Highest Transaction:

In [41]:
df["total_price"].max()

433.99

###Lowest Transaction:

In [42]:
df["total_price"].min()

1.21

###Total Tax Collected:

In [43]:
df["tax"].sum()

np.float64(7758.01)

###Total Reward Points:

In [44]:
df["reward_points"].sum()

np.int64(6057)

#16️⃣ Branch-wise Revenue

##Ab actual analysis start:

In [45]:
df.groupby("branch")["total_price"].sum()

branch
A    82811.64
B    35772.26
Name: total_price, dtype: float64

###Isse pata chalega:

###Har branch se kitni total sales hui.

#Quantity ke liye:

In [46]:
df.groupby("branch")["quantity"].sum()

branch
A    6982
B    3355
Name: quantity, dtype: int64

#Average Transaction Ke Liye:

In [47]:
df.groupby("branch")["total_price"].mean()

branch
A    122.865935
B    109.730859
Name: total_price, dtype: float64

#17️⃣ City-wise Revenue

In [48]:
df.groupby("city")["total_price"].sum()

city
Chicago        42584.71
Los Angeles    35772.26
New York       40226.93
Name: total_price, dtype: float64

#Aur Quantity:

In [49]:
df.groupby("city")["quantity"].sum()

city
Chicago        3638
Los Angeles    3355
New York       3344
Name: quantity, dtype: int64

#18️⃣ Product Category Analysis

In [50]:
df.groupby("product_category")["total_price"].sum()

product_category
Beverages        22983.32
Fruits           26197.45
Household        21615.84
Personal Care    27050.18
Stationery       20737.11
Name: total_price, dtype: float64

##Quantity:

In [51]:
df.groupby("product_category")["quantity"].sum()

product_category
Beverages        1952
Fruits           2286
Household        1908
Personal Care    2278
Stationery       1913
Name: quantity, dtype: int64

##Average Prices:

In [52]:
df.groupby("product_category")["unit_price"].mean()

product_category
Beverages        11.113155
Fruits           10.845263
Household        10.930707
Personal Care    11.246923
Stationery       10.038636
Name: unit_price, dtype: float64

#19️⃣ Customer Type Analysis

In [53]:
df.groupby("customer_type")["total_price"].sum()

customer_type
Member    63213.63
Normal    55370.27
Name: total_price, dtype: float64

##Aur Transaction Count:

In [54]:
df["customer_type"].value_counts()

customer_type
Member    516
Normal    484
Name: count, dtype: int64

#20️⃣ Gender Analysis

In [55]:
df.groupby("gender")["total_price"].sum()

gender
Female    54265.45
Male      64318.45
Name: total_price, dtype: float64

#🔥 21️⃣ Sabse useful — Ek saath multiple metrics

##Ye bahut important Pandas pattern hai:

In [56]:
df.groupby("product_category").agg({
    "total_price": "sum",
    "quantity": "sum",
    "unit_price": "mean",
    "tax": "sum"
})

                  total_price  quantity  unit_price      tax
product_category
Beverages            22983.32      1952   11.113155  1503.65
Fruits               26197.45      2286   10.845263  1713.86
Household            21615.84      1908   10.930707  1414.13
Personal Care        27050.18      2278   11.246923  1769.66
Stationery           20737.11      1913   10.038636  1356.71

#🧠 Day 34 ka actual conclusion

##Ab tumne dataset ko sirf inspect nahi kiya, balki basic business questions bhi answer karne start kar diye:


Dataset

   ↓

Understand structure

   ↓

Check data quality

   ↓

Understand categories

   ↓

Calculate KPIs

   ↓

Compare branches

   ↓

Compare cities

   ↓

Compare products

   ↓

Understand customers