#🐼 Day 32 — Pandas DataFrame Basics

##Pandas ka sabse important structure DataFrame hai.

##Agar Series ko ek single column samjho, toh DataFrame ko complete table samjho.

####           Name   Age   Marks
####Index 0    Rahul   20     85
####Index 1    Aman    21     72
####Index 2    Priya   20     91

##Real-world CSV/Kaggle datasets bhi generally DataFrame ke form mein hi load honge.

#🎯 Day 32 Goals

##Aaj hum seekhenge:

###DataFrame kya hota hai
###DataFrame create karna
###Dictionary se DataFrame
###List of lists se DataFrame
###Rows aur columns samajhna
###head() and tail()
###shape
###columns
###index
###dtypes
###Single column select karna
###Multiple columns select karna
###New column add karna
###Existing column modify karna
###Column delete karna
###Basic statistics
###Practical Student DataFrame
###DataFrame ka mind template

#1️⃣ What is a DataFrame?

##DataFrame = 2-dimensional tabular data structure

##Isko Excel table jaisa samajh sakte ho.

##Example:

Name	Age	Marks

Rahul	20	85

Aman	21	72

Priya	20	91

##Yahan:

Name, Age, Marks → columns

Rahul, Aman, Priya → records/rows

0, 1, 2 → default index

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya"],
    "Age": [20, 21, 20],
    "Marks": [85, 72, 91]
})

print(df)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91

#2️⃣ DataFrame from Dictionary

##Ye DataFrame banane ka common method hai.

In [2]:
data = {
    "Name": ["Rahul", "Aman", "Priya", "Neha"],
    "Age": [20, 21, 20, 22],
    "Marks": [85, 72, 91, 68]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91
3   Neha   22     68

#3️⃣ DataFrame from List of Lists

##DataFrame nested lists se bhi bana sakte hain.

In [3]:
data = [
    ["Rahul", 20, 85],
    ["Aman", 21, 72],
    ["Priya", 20, 91]
]

df = pd.DataFrame(
    data,
    columns=["Name", "Age", "Marks"]
)

print(df)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91

##🧠 Important

###Yahan columns= se hum column names define kar rahe hain.

#4️⃣ Rows and Columns

##DataFrame ko samajhne ke liye ye distinction bahut important hai.

###          Name    Age    Marks
###0         Rahul    20      85
###1         Aman     21      72
###2         Priya    20      91
##Rows
###0 → Rahul
###1 → Aman
###2 → Priya

##Har row ek record hai.

###Columns
###Name
###Age
###Marks

##Har column ek variable/feature hai.

#5️⃣ head()

##DataFrame ki starting rows dekhne ke liye:

df.head()

##By default first 5 rows show karta hai.

#Agar first 2 rows chahiye:

##df.head(2)
#🧠 Real-world use

##Jab hum Kaggle CSV load karenge:

##df = pd.read_csv("dataset.csv")

#df.head()

##Ye sabse pehle use hone wale commands mein se ek hoga.

In [20]:
df.head()
df.head(2)

    Name  Age  Marks        Performance  Marks_Percentage  Passed
0  Rahul   20     85               Good                85    True
1   Aman   21     72  Needs Improvement                72    True

#6️⃣ tail()

##Last rows dekhne ke liye:

##df.tail()

#Last 2 rows:

##df.tail(2)
#Difference
###head() → beginning
###tail() → ending

In [19]:
df.tail()

df.tail(2)

    Name  Age  Marks        Performance  Marks_Percentage  Passed
1   Aman   21     72  Needs Improvement                72    True
2  Priya   20     91               Good                91    True

#7️⃣ shape

##DataFrame mein kitni rows aur columns hain:

print(df.shape)

##Example:

(4, 3)

##Means:

4 rows

3 columns

##Separately:

print("Rows:", df.shape[0])

print("Columns:", df.shape[1])
#🧠 Important
df.shape

##returns:

(rows, columns)

In [18]:
print(df.shape)

print("Rows:", df.shape[0])

print("Columns:", df.shape[1])

(3, 6)
Rows: 3
Columns: 6

#8️⃣ columns

##DataFrame ke column names dekhne ke liye:

print(df.columns)

##Agar normal Python list chahiye:

print(df.columns.tolist())

##Output:

['Name', 'Age', 'Marks']

In [17]:
print(df.columns)
print(df.columns.tolist())

Index(['Name', 'Age', 'Marks', 'Performance', 'Marks_Percentage', 'Passed'], dtype='object')
['Name', 'Age', 'Marks', 'Performance', 'Marks_Percentage', 'Passed']

#9️⃣ index

##DataFrame ke row labels:

print(df.index)

##Output kuch aisa ho sakta hai:

RangeIndex(start=0, stop=4, step=1)

##Default index:

0

1

2

3

In [16]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

#🔟 dtypes

##Har column ka data type check karne ke liye:

print(df.dtypes)

##Example:

Name     object

Age       int64

Marks     int64

dtype: object

##Generally:

Name  → text

Age   → integer

Marks → integer
#🧠 Real Data Analysis mein important

##Later jab real dataset load karenge, dtypes se pata chalega ki columns numerical hain, categorical hain, dates hain, etc.

#1️⃣1️⃣ Selecting a Single Column

##Suppose hume sirf Marks chahiye:

marks = df["Marks"]

print(marks)

###Ye Series return karega.

##Check:

print(type(marks))

##Output:

<class 'pandas.core.series.Series'>
#🧠 Very Important
df["Marks"]

→ Series

In [14]:
marks = df["Marks"]

print(marks)

0    85
1    72
2    91
Name: Marks, dtype: int64

In [15]:
print(type(marks))

<class 'pandas.core.series.Series'>

#1️⃣2️⃣ Selecting Multiple Columns

##Suppose hume Name aur Marks chahiye:

selected = df[["Name", "Marks"]]

print(selected)

##Ye DataFrame return karega.

print(type(selected))
#Remember this difference:
df["Marks"]

→ Series

df[["Name", "Marks"]]

→ DataFrame

###Double brackets ko yaad rakhna.

In [12]:
selected = df[["Name", "Marks"]]

print(selected)

    Name  Marks
0  Rahul     85
1   Aman     72
2  Priya     91

In [13]:
print(type(selected))

<class 'pandas.core.frame.DataFrame'>

#1️⃣3️⃣ Adding a New Column

##DataFrame mein new column easily add kar sakte hain.

df["Passed"] = df["Marks"] >= 40

print(df)

##Output:

Name  Age  Marks  Passed

0  Rahul   20     85    True

1   Aman   21     72    True

2  Priya   20     91    True

3   Neha   22     68    True

##Yahan:

df["Marks"] >= 40

###ek Boolean Series create karta hai.

###Usko Passed column mein store kar diya.

In [11]:
df["Passed"] = df["Marks"] >= 40

print(df)

    Name  Age  Marks        Performance  Marks_Percentage  Passed
0  Rahul   20     85               Good                85    True
1   Aman   21     72  Needs Improvement                72    True
2  Priya   20     91               Good                91    True

#1️⃣4️⃣ Creating a Calculated Column

##Existing columns se new column bana sakte hain.

##Example:

df["Marks_Percentage"] = df["Marks"]

print(df)

##Marks already 100 mein se hain, isliye percentage same value hogi.

##Another useful example:

df["Performance"] = df["Marks"].apply(
    lambda x: "Good" if x >= 75 else "Needs Improvement"
)

print(df)
#🧠 Important

##Data Analysis mein hum frequently derived/calculated columns create karenge.

For example:


Revenue
  
   ↓

Profit
  
   ↓

Profit Margin

##ya


Date
  
   ↓

Month
  
   ↓

Monthly Sales

##Ye concept later real datasets mein bahut important hoga.

In [10]:
df["Marks_Percentage"] = df["Marks"]

print(df)

    Name  Age  Marks        Performance  Marks_Percentage
0  Rahul   20     85               Good                85
1   Aman   21     72  Needs Improvement                72
2  Priya   20     91               Good                91

In [7]:
df["Performance"] = df["Marks"].apply(
    lambda x: "Good" if x >= 75 else "Needs Improvement"
)

#1️⃣5️⃣ Modifying an Existing Column

##Existing column ko modify bhi kar sakte hain.

##Fresh DataFrame banate hain:

students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya"],
    "Age": [20, 21, 20],
    "Marks": [85, 72, 91]
})

students["Age"] = students["Age"] + 1

print(students)

###Har age mein 1 add ho jayega.

#🧠 Important

##Assignment ke through existing column overwrite ho sakta hai.

In [9]:
students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya"],
    "Age": [20, 21, 20],
    "Marks": [85, 72, 91]
})

students["Age"] = students["Age"] + 1

print(students)

    Name  Age  Marks
0  Rahul   21     85
1   Aman   22     72
2  Priya   21     91

#1️⃣6️⃣ Deleting a Column

##drop() use kar sakte hain.

df_without_performance = df.drop(
    "Performance",
    axis=1
)

print(df_without_performance)
axis

##Abhi ke liye yaad rakho:

axis=0 → rows

axis=1 → columns

##Isliye:

df.drop("Performance", axis=1)

##means:

###Performance column remove karo.

In [8]:
df_without_performance = df.drop(
    "Performance",
    axis=1
)

print(df_without_performance)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91

#1️⃣7️⃣ Basic Statistics

##Pandas numerical columns ke saath directly calculations kar sakta hai.

In [21]:
print("Mean:", df["Marks"].mean())
print("Maximum:", df["Marks"].max())
print("Minimum:", df["Marks"].min())
print("Total:", df["Marks"].sum())
print("Standard Deviation:", df["Marks"].std())

Mean: 82.66666666666667
Maximum: 91
Minimum: 72
Total: 248
Standard Deviation: 9.71253485622231

#1️⃣8️⃣ describe()

##Numerical data ka statistical summary:

In [22]:
df.describe()

             Age      Marks  Marks_Percentage
count   3.000000   3.000000          3.000000
mean   20.333333  82.666667         82.666667
std     0.577350   9.712535          9.712535
min    20.000000  72.000000         72.000000
25%    20.000000  78.500000         78.500000
50%    20.000000  85.000000         85.000000
75%    20.500000  88.000000         88.000000
max    21.000000  91.000000         91.000000

#🧠 Why important?

#Real dataset load karne ke baad:

##df.describe()

###se hume numerical data ka quick statistical overview mil jata hai.

#1️⃣9️⃣ Practical Student Dataset

##Ab ek proper practical example karte hain.

In [23]:
students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Age": [20, 21, 20, 22, 21],
    "Python": [85, 72, 91, 64, 78],
    "Math": [80, 68, 94, 70, 75],
    "DSA": [82, 70, 89, 65, 80]
})

print(students)

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
1   Aman   21      72    68   70
2  Priya   20      91    94   89
3   Neha   22      64    70   65
4  Rohit   21      78    75   80

In [24]:
students["Average"] = students[
    ["Python", "Math", "DSA"]
].mean(axis=1)

print(students)

    Name  Age  Python  Math  DSA    Average
0  Rahul   20      85    80   82  82.333333
1   Aman   21      72    68   70  70.000000
2  Priya   20      91    94   89  91.333333
3   Neha   22      64    70   65  66.333333
4  Rohit   21      78    75   80  77.666667

#2️⃣0️⃣ Filter High Performers

##Suppose average ≥ 75 wale students chahiye:

In [25]:
high_performers = students[
    students["Average"] >= 75
]

print(high_performers)

    Name  Age  Python  Math  DSA    Average
0  Rahul   20      85    80   82  82.333333
2  Priya   20      91    94   89  91.333333
4  Rohit   21      78    75   80  77.666667

#2️⃣1️⃣ Highest Python Score

In [26]:
highest_python = students["Python"].max()

print("Highest Python score:", highest_python)

Highest Python score: 91

#2️⃣2️⃣ Student with Highest Average

In [27]:
top_student = students.loc[
    students["Average"].idxmax()
]

print(top_student)

Name           Priya
Age               20
Python            91
Math              94
DSA               89
Average    91.333333
Name: 2, dtype: object

#🧠 DataFrame Mind Template

Jab bhi DataFrame ka question aaye, ye flow mind mein rakhna:

                 DATAFRAME
                     ↓
          Understand rows/columns
                     ↓
               INSPECT DATA
                     ↓
       head() / tail() / shape
       columns / index / dtypes
                     ↓
             SELECT DATA
                     ↓
       df["column"]
       df[["col1", "col2"]]
                     ↓
          CREATE / MODIFY
                     ↓
       New calculated columns
                     ↓
               ANALYZE
                     ↓
      mean / max / min / sum
               describe()
                     ↓
                FILTER
                     ↓
             Conditions

#📝 Day 32 Practice
#Q1

##5 students ka DataFrame create karo:

###Name
###Age
###Marks

In [29]:
students=pd.DataFrame({
    "Name":["Rahul","Aman","Priya","Neha","Rohit"],
    "Age":[20,21,20,22,21],
    "Marks":[85,72,91,64,78]
})
print(students)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91
3   Neha   22     64
4  Rohit   21     78

#Q2

##Dictionary se DataFrame banao:

###Product
###Price
###Quantity

##Aur first 3 rows head() se print karo.

In [30]:
data = {
    "Product": ["Book", "Copy", "Pen", "Pencil"],
    "Price": [20, 40, 60, 80],
    "Quantity": [10, 20, 30, 40]
}

df = pd.DataFrame(data)

print(df)
print(df.head(3))

  Product  Price  Quantity
0    Book     20        10
1    Copy     40        20
2     Pen     60        30
3  Pencil     80        40
  Product  Price  Quantity
0    Book     20        10
1    Copy     40        20
2     Pen     60        30

#Q3

##6-row DataFrame create karke print karo:

###shape
###columns
###index
###dtypes

In [31]:
data=pd.DataFrame({
    "Name":["Rahul","Aman","Priya","Neha","Rohit","Priya"],
    "Age":[20,21,20,22,21,20],
    "Marks":[85,72,91,64,78,90]
})
print(data)
print(data.shape)
print(data.columns)
print(data.index)
print(data.dtypes)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     72
2  Priya   20     91
3   Neha   22     64
4  Rohit   21     78
5  Priya   20     90
(6, 3)
Index(['Name', 'Age', 'Marks'], dtype='object')
RangeIndex(start=0, stop=6, step=1)
Name     object
Age       int64
Marks     int64
dtype: object

#Q4

##Student DataFrame se:

###Sirf Name select karo.
###Name + Marks select karo.

In [32]:
students=pd.DataFrame({
    "Name":["Rahul","Aman","Priya","Neha","Rohit"],
    "Age":[20,21,20,22,21],
    "Marks":[85,72,91,64,78]
})
print(students["Name"])
print(students[["Name","Marks"]])

0    Rahul
1     Aman
2    Priya
3     Neha
4    Rohit
Name: Name, dtype: object
    Name  Marks
0  Rahul     85
1   Aman     72
2  Priya     91
3   Neha     64
4  Rohit     78

#Q5

#Marks ≥ 40 ke basis par:

###Passed = True/False

##column create karo.

In [35]:
passed_students=students["Marks"]>40
print(passed_students)

0    True
1    True
2    True
3    True
4    True
Name: Marks, dtype: bool

#Q6

##Teen subjects:

###Python
###Math
###DSA

##ka average calculate karke Average column banao.

In [36]:
students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Age": [20, 21, 20, 22, 21],
    "Python": [85, 72, 91, 64, 78],
    "Math": [80, 68, 94, 70, 75],
    "DSA": [82, 70, 89, 65, 80]
})
print(students)
students["Average"] = students[
    ["Python", "Math", "DSA"]
].mean(axis=1)

print(students["Average"])

    Name  Age  Python  Math  DSA
0  Rahul   20      85    80   82
1   Aman   21      72    68   70
2  Priya   20      91    94   89
3   Neha   22      64    70   65
4  Rohit   21      78    75   80
0    82.333333
1    70.000000
2    91.333333
3    66.333333
4    77.666667
Name: Average, dtype: float64

#Q7

##Find:

###Average marks
###Highest marks
###Lowest marks
###Total marks

In [41]:
import pandas as pd

students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Age": [20, 21, 20, 22, 21],
    "Python": [85, 72, 91, 64, 78],
    "Math": [80, 68, 94, 70, 75],
    "DSA": [82, 70, 89, 65, 80]
})

# Calculate the average of the three subjects
students["Average"] = students[["Python", "Math", "DSA"]].mean(axis=1)

print("--- Average Column ---")
print(students["Average"])

# Corrected column name from "Marks" to "Average"
print("\nMax Average:", students["Average"].max())
print("Min Average:", students["Average"].min())
print("Sum of Averages:", students["Average"].sum())

--- Average Column ---
0    82.333333
1    70.000000
2    91.333333
3    66.333333
4    77.666667
Name: Average, dtype: float64

Max Average: 91.33333333333333
Min Average: 66.33333333333333
Sum of Averages: 387.66666666666663

#Q8

##Numerical DataFrame par:

###describe()

##use karo aur output observe karo.

In [42]:
print(students.describe())

            Age     Python       Math        DSA    Average
count   5.00000   5.000000   5.000000   5.000000   5.000000
mean   20.80000  78.000000  77.400000  77.200000  77.533333
std     0.83666  10.606602  10.382678   9.628084   9.945965
min    20.00000  64.000000  68.000000  65.000000  66.333333
25%    20.00000  72.000000  70.000000  70.000000  70.000000
50%    21.00000  78.000000  75.000000  80.000000  77.666667
75%    21.00000  85.000000  80.000000  82.000000  82.333333
max    22.00000  91.000000  94.000000  89.000000  91.333333

#Q9

##Average ≥ 75 wale students filter karo.

In [45]:
topper=students[students["Average"]>=75]
print(topper)

    Name  Age  Python  Math  DSA    Average
0  Rahul   20      85    80   82  82.333333
2  Priya   20      91    94   89  91.333333
4  Rohit   21      78    75   80  77.666667

#🔥 Q10 — Mini DataFrame Analyzer

##At least 6 students ka DataFrame banao with:

###Name
###Age
###Python
###Math
###DSA

##Then:

###Har student ka average calculate karo.
###Highest average find karo.
###Lowest average find karo.
###Average ≥ 75 students filter karo.
###Highest Python marks wala student find karo.
###Sirf Name aur Average display karo.
###DataFrame ka shape print karo.
###describe() use karo.

In [46]:
import pandas as pd

students = pd.DataFrame({
    "Name": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Age": [20, 21, 20, 22, 21],
    "Python": [85, 72, 91, 64, 78],
    "Math": [80, 68, 94, 70, 75],
    "DSA": [82, 70, 89, 65, 80]
})
# Calculate the average of the three subjects
students["Average"] = students[["Python", "Math", "DSA"]].mean(axis=1)

print("--- Average Column ---")
print(students["Average"])

# Corrected column name from "Marks" to "Average"
print("\nMax Average:", students["Average"].max())
print("Min Average:", students["Average"].min())
topper=students[students["Average"]>=75]
print(topper)
print(students.loc[students["Python"].idxmax()])
print(students[["Name","Average"]])
print(students.shape)
print(students.describe())
print("Sum of Averages:", students["Average"].sum())

--- Average Column ---
0    82.333333
1    70.000000
2    91.333333
3    66.333333
4    77.666667
Name: Average, dtype: float64

Max Average: 91.33333333333333
Min Average: 66.33333333333333
    Name  Age  Python  Math  DSA    Average
0  Rahul   20      85    80   82  82.333333
2  Priya   20      91    94   89  91.333333
4  Rohit   21      78    75   80  77.666667
Name           Priya
Age               20
Python            91
Math              94
DSA               89
Average    91.333333
Name: 2, dtype: object
    Name    Average
0  Rahul  82.333333
1   Aman  70.000000
2  Priya  91.333333
3   Neha  66.333333
4  Rohit  77.666667
(5, 6)
            Age     Python       Math        DSA    Average
count   5.00000   5.000000   5.000000   5.000000   5.000000
mean   20.80000  78.000000  77.400000  77.200000  77.533333
std     0.83666  10.606602  10.382678   9.628084   9.945965
min    20.00000  64.000000  68.000000  65.000000  66.333333
25%    20.00000  72.000000  70.000000  70.000000  70.000000
50%    21.00000  78.000000  75.000000  80.000000  77.666667
75%    21.00000  85.000000  80.000000  82.000000  82.333333
max    22.00000  91.000000  94.000000  89.000000  91.333333
Sum of Averages: 387.66666666666663